

GET ALL POSTS:
http://localhost:4040/posts
https://socialmediasite-ok41.onrender.com/posts


POST ONE POST:
http://localhost:4040/posts
https://socialmediasite-ok41.onrender.com/posts
{
    "text": "newPost",
    "image": "imagepath",
    "date": "2/10/24",
    "number_of_likes": 1,
    "user_name": "myName",
    "user_avatar": "myAvatar"
}


UPDATE (PUT) ONE POST:
http://localhost:4040/posts/update/{id}
https://socialmediasite-ok41.onrender.com/posts/update/{id}
{
    "text": "updatedPost",
    "image": "updatedimagepath",
    "date": "2/17/24",
    "number_of_likes": 1,
    "user_name": "myName",
    "user_avatar": "myAvatar"
}


DELETE ONE POST:
http://localhost:4040/posts/delete/{id}
https://socialmediasite-ok41.onrender.com/posts/delete/{id}